name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    # main 分支
    if: github.ref == 'refs/heads/main'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker/go-1.20/
          push: true
          tags: linfeiyang/docker:go1.20
  php:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./php/5.6-fpm-nginx/
          push: true
          tags: linfeiyang/php:php-5.6-fpm-nginx
      #-
      #  name: Build and push
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: ./php/8.2.4-fpm-nginx/
      #    push: true
      #    tags: linfeiyang/php:php-8.2.4-fpm-nginx
      #-
      #  name: Build and push
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: ./php/7.0.33-fpm-nginx/
      #    push: true
      #    tags: linfeiyang/php:php-7.0.33-fpm-nginx
       
   